### ISSUE TITLE
Deal with flask app during development phase with stripe

### ISSUE THREAD

**Issue by Emirov** [diwash007/Flask-O-shop#1]
There is no mentioned in the Readme how to deal with stripe in development step. 
See  https://blog.miguelgrinberg.com/post/accept-credit-card-payments-in-flask-with-stripe-checkout
To test webhooks is that during development the Flask application runs privately inside your own computer on http://localhost:5000, so a webhook in this application is not reachable by Stripe. There is a way to work around this problem with the Stripe CLI. Another option is to use the ngrok utility.

**Comment by diwash007** [comment]
yes, we have to use "stripe listen" with stripe CLI for that to work.
