### ISSUE TITLE
Issue with price ID

### ISSUE THREAD

**Issue by Emirov** [diwash007/Flask-O-shop#3]
Get this error when trying to use the same db with another test app:
Request req_LUEtpFa5SWJj8s: No such price: 'price_1Jk8KjBZlBPWG6ECQXNqcKhR'
Not mentioned the policy used to define the price_id.
Did you use this one https://stripe.com/docs/api/prices/create or there are any other method.
Also, is it mandatory to define a price id for each different amount.

**Comment by diwash007** [comment]
yes, you have to use the price id for each product from your stripe product list.
